# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_thumbnail',
            field=models.ImageField(default='', upload_to='photo/thumbnail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(upload_to='album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
