# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('through', '0003_auto_20161006_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='피자',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('피자이름', models.CharField(max_length=100)),
            ],
        ),
    ]
