# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='post'),
        ),
    ]
