# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('through', '0004_피자'),
    ]

    operations = [
        migrations.DeleteModel(
            name='피자',
        ),
    ]
