# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('img_profile', models.ImageField(blank=True, upload_to='user')),
                ('img_profile_thumbnail', models.ImageField(blank=True, upload_to='user/thumbnail')),
                ('is_facebook_user', models.BooleanField(default=False)),
                ('facebook_id', models.CharField(blank=True, max_length=50)),
                ('facebook_token', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
