# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161020_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
