# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20161018_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
