# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20161018_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_img',
            field=models.ImageField(blank=True, upload_to='video'),
        ),
    ]
