# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='강의 제목')),
                ('description', models.TextField(blank=True, verbose_name='강의 설명')),
                ('content', markdownx.models.MarkdownxField(blank=True, verbose_name='강의 내용')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='해당 코스')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lecture', verbose_name='해당 강의'),
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='영상 설명'),
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='영상 제목'),
        ),
    ]
