# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20161128_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturevideo',
            old_name='course',
            new_name='lecture',
        ),
    ]
