# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20161128_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='강의 섹션')),
                ('description', models.TextField(blank=True, verbose_name='섹션 설명')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='해당 코스')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.AddField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.LectureSection', verbose_name='해당 섹션'),
            preserve_default=False,
        ),
    ]
