# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20161128_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturesection',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
