# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20161128_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('priority',)},
        ),
        migrations.AlterModelOptions(
            name='lecturesection',
            options={'ordering': ('priority',)},
        ),
    ]
