# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_auto_20161010_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='other_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='other_group_set', to='ref.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='ref.Group'),
        ),
    ]
