# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0004_childa_childb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childa',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_childa_related', to='ref.Group'),
        ),
        migrations.AlterField(
            model_name='childb',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_childb_related', to='ref.Group'),
        ),
    ]
