# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0005_auto_20161010_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ref.person',),
        ),
    ]
