# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
