# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastcampusUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='아이디')),
                ('last_name', models.CharField(max_length=30, verbose_name='성')),
                ('first_name', models.CharField(max_length=30, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('github', models.CharField(max_length=50, verbose_name='GitHub계정 이름')),
                ('age', models.IntegerField(default=0, verbose_name='나이')),
                ('objective_type', models.CharField(choices=[('job', '취업'), ('change', '커리어 전환'), ('foundation', '창업'), ('interest', '흥미')], max_length=20, verbose_name='목표')),
                ('objective_detail', models.TextField(blank=True, verbose_name='상세 목표')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='수강 코스')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
